# Generated by Django 4.2.7 on 2023-11-09 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_qty', models.IntegerField()),
                ('drug_exp', models.DateField()),
                ('drug_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.d_type')),
            ],
        ),
    ]
